# Generated by Django 4.0.2 on 2022-03-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime_com',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datetime_post',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='_category',
            new_name='category',
        ),
    ]
